### ISSUE TITLE
Making a release

### ISSUE THREAD

**Issue by lima-limon-inc** [crmsnbleyd/uiua-mode#18]
Hello uiua-mode team!

Thank you very much for your work! 

Would you mind making a Github release? Even if it's labeled as unstable or something. It makes packaging the program easier for package managers for distros.

I would like to make one for Gentoo and having a release to point to really makes things simpler.

Is that a possibility? Thanks in advance

**Comment by purcell** [comment]
No worries, done, thanks!

https://github.com/crmsnbleyd/uiua-mode/releases/tag/v0.1.0

**Comment by lima-limon-inc** [comment]
Thanks!!

**Comment by lima-limon-inc** [comment]
https://github.com/lima-limon-inc/lemon-lime-overlay/blob/main/app-emacs/uiua-mode/uiua-mode-0.1.0.ebuild

Ebuild is done :partying_face: .

Thank you @purcell for the help.
